import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {indexedDB} from 'fake-indexeddb';
const compile = source => 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2023}}).outputText).toString('base64');
globalThis.indexedDB=indexedDB;
const {indexedDbRepository: repository}=await import(compile(fs.readFileSync('src/platform/web/indexedDbRepository.ts','utf8')));
const storage=new Map();globalThis.sessionStorage={getItem:key=>storage.get(key)||null,setItem:(key,value)=>storage.set(key,String(value)),removeItem:key=>storage.delete(key)};
globalThis.window=new EventTarget();globalThis.__auth={currentUser:{uid:'user-a',getIdToken:async()=> 'fresh-firebase-token'}};
Object.defineProperty(globalThis,'navigator',{value:{onLine:false},configurable:true});
let handler=async()=>{throw new Error('offline');};globalThis.fetch=(...args)=>handler(...args);
globalThis.__repository=repository;
let source=fs.readFileSync('src/core/localData.ts','utf8').replace('import { auth } from "../firebase";','const auth=globalThis.__auth;').replace('import { customerRepository as repository } from "./customerRepository";','const repository=globalThis.__repository;');
const engine=await import(compile(source));
function connect(id='connection-a') {storage.set('bankSetuOfflineUntil',String(Date.now()+3600000));storage.set('bankSetuTenantId','tenant-a');storage.set('bankSetuConnectionId',id);storage.set('bankSetuConnectionMode','option-b');storage.set('bankSetuWorkspaceReady','true');storage.set('bankSetuBridgeUrl','https://script.google.com/macros/s/bridge/exec');storage.set('bankSetuAccountRole','client_admin');}
const customer={name:'Alice',accountNo:'1001',enrolId:'C001',uidaiNo:'123456789012'};
const request=body=>engine.localDataFetch('https://script.google.com/macros/s/bridge/exec',{method:'POST',body:JSON.stringify({...body,idToken:'never-store-this'})}).then(response=>response.json());
test('IndexedDB persists customer and queue in one atomic transaction and rolls back failed changes',async()=>{
 await repository.transact('atomic',state=>{state.records.push({recordId:'kept'});state.operations.push({operationId:'kept'});});
 await assert.rejects(repository.transact('atomic',state=>{state.records.push({recordId:'lost'});throw Error('abort');}));
 const state=await repository.read('atomic');assert.equal(state.records.length,1);assert.equal(state.operations.length,1);
});
test('offline save, search, retry, connection isolation and explicit conflict review',async()=>{
 connect();const saved=await request({action:'saveCustomer',customer});assert(saved.success&&saved.queued);
 let state=await repository.read('user-a:tenant-a:connection-a');assert.equal(state.records.length,1);assert.equal(state.operations.length,1);assert(!JSON.stringify(state).includes('never-store-this'));
 const search=await request({action:'searchCustomer',query:'alice'});assert.equal(search.customer.name,'Alice');assert.equal(search.customer.recordId,saved.recordId);
 connect('connection-b');const miss=await request({action:'searchCustomer',query:'alice'});assert.equal(miss.success,false);assert.equal((await repository.read('user-a:tenant-a:connection-a')).operations.length,1);
 connect();navigator.onLine=true;let sent=[];
 handler=async(_url,init)=>{const body=JSON.parse(init.body);sent.push(body);throw Error('timeout after cloud commit');};
 await assert.rejects(engine.syncNow());assert.equal((await repository.read('user-a:tenant-a:connection-a')).operations.length,1);
 const originalId=sent[0].operation.operationId;
 handler=async(_url,init)=>{const body=JSON.parse(init.body);if(body.action==='syncCustomerOperation'){sent.push(body);return new Response(JSON.stringify({success:true,rowNumber:9,revision:'r1',customer:{...customer,recordId:saved.recordId,revision:'r1',rowNumber:9}}));}return new Response(JSON.stringify({success:true,customers:[],fullSnapshot:false}));};
 await engine.syncNow();assert.equal(sent.at(-1).operation.operationId,originalId);state=await repository.read('user-a:tenant-a:connection-a');assert.equal(state.operations.length,0);assert.equal(state.records[0].rowNumber,9);
 navigator.onLine=false;await request({action:'updateCustomer',rowNumber:9,customer:{...customer,name:'Local edit'}});navigator.onLine=true;
 handler=async(_url,init)=>{const body=JSON.parse(init.body);return new Response(JSON.stringify(body.action==='syncCustomerOperation'?{success:false,code:'CONFLICT',message:'Changed remotely',customer:{...customer,name:'Cloud edit',recordId:saved.recordId,revision:'r2',rowNumber:4}}:{success:true,customers:[],fullSnapshot:false}));};
 await engine.syncNow();const conflicts=await engine.getConflicts();assert.equal(conflicts[0].remoteCustomer.name,'Cloud edit');assert.equal((await repository.read('user-a:tenant-a:connection-a')).records[0].customer.name,'Local edit');
 storage.set('bankSetuAccountRole','client_user');await assert.rejects(engine.resolveConflict(conflicts[0].operationId,'local'),/Admin/);storage.set('bankSetuAccountRole','client_admin');
 await engine.resolveConflict(conflicts[0].operationId,'cloud');state=await repository.read('user-a:tenant-a:connection-a');assert.equal(state.operations.length,0);assert.equal(state.records[0].customer.name,'Cloud edit');assert.equal(state.records[0].rowNumber,4);
});
