import { useEffect, useMemo, useRef, useState } from "react";
import { getLocalExportCustomers, getLocalStatus } from "./core/localData";
import { buildCustomerXlsx, saveCustomerXlsx } from "./exportXlsx";

type Row=Record<string,unknown>;
const value=(row:Row,key:string)=>String(row[key]??"");
export default function CustomerExcelExport({close}:{close:()=>void}){
  const [records,setRecords]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[partial,setPartial]=useState(false);
  const [mode,setMode]=useState<"all"|"search"|"date"|"range">("all"),[query,setQuery]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState("");
  const [chosen,setChosen]=useState<Set<string>>(new Set()),[photos,setPhotos]=useState(true),[allFields,setAllFields]=useState(true),[resize,setResize]=useState(true);
  const [progress,setProgress]=useState(""),controller=useRef<AbortController|null>(null);
  useEffect(()=>{let active=true;void Promise.all([getLocalExportCustomers(),getLocalStatus()]).then(([data,status])=>{if(active){setRecords(data);setPartial(status.downloading||status.cacheLimited);setLoading(false);}}).catch(reason=>{if(active){setError(reason instanceof Error?reason.message:"Local records could not be read.");setLoading(false);}});return()=>{active=false;controller.current?.abort();};},[]);
  const key=(row:Row)=>value(row,"recordId")||value(row,"enrolId")||value(row,"accountNo");
  const matches=useMemo(()=>records.filter(row=>["name","accountNo","enrolId","contact","mobile"].some(field=>value(row,field).toLowerCase().includes(query.trim().toLowerCase()))),[records,query]);
  const filtered=useMemo(()=>{
    if(mode==="search")return matches.filter(row=>chosen.has(key(row)));
    if(mode==="date")return records.filter(row=>{const raw=value(row,"createdAt")||value(row,"entryDate")||value(row,"createdDate");const day=raw.slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(day)&&(!from||day>=from)&&(!to||day<=to);});
    if(mode==="range") {const first=records.filter(row=>value(row,"enrolId")===from.trim()),last=records.filter(row=>value(row,"enrolId")===to.trim());if(first.length!==1||last.length!==1)return [];const start=records.indexOf(first[0]),end=records.indexOf(last[0]);return end<start?[]:records.slice(start,end+1);}
    return records;
  },[mode,matches,chosen,records,from,to]);
  const run=async()=>{if(!filtered.length){setError("Select at least one valid local customer record.");return;}if(partial&&!window.confirm(`Local download is incomplete. Export only ${filtered.length} available record(s)?`))return;
    setError("");setProgress("Preparing local Excel export…");const signal=new AbortController();controller.current=signal;
    try{const blob=await buildCustomerXlsx(filtered,{photos,allFields,autoResize:resize,signal:signal.signal,progress:(done,total)=>setProgress(`Preparing ${done} / ${total} customers…`)});if(signal.signal.aborted)return;setProgress("Saving Excel file…");await saveCustomerXlsx(blob);setProgress(`Excel ready: ${filtered.length} local customers${partial?" (partial local export)":""}.`);}catch(reason){if(!signal.signal.aborted)setError(reason instanceof Error?reason.message:"Excel export failed.");}finally{controller.current=null;}};
  const stop=()=>{controller.current?.abort();controller.current=null;setProgress("Export cancelled.");};
  return <div role="dialog" aria-modal="true" aria-label="Export Customer Data Excel" style={s.backdrop}><div style={s.panel}>
    <header style={s.header}><div><h2 style={{margin:0}}>Export Customer Data (Excel)</h2><p style={{margin:"5px 0 0"}}>Export current tenant's local customer data with available photos.</p></div><button onClick={close} style={s.close} aria-label="Close">×</button></header>
    {loading?<p>Loading local customers…</p>:<div style={s.columns}><section style={s.modes}>
      {([['all','All Customers'],['search','Search Customers'],['date','Date Range'],['range','Custom Range']] as const).map(([id,label])=><label key={id} style={{...s.choice,background:mode===id?"#e5f6ee":"#f5f8fc"}}><input type="radio" checked={mode===id} onChange={()=>setMode(id)}/><strong>{label}</strong></label>)}
      {mode==="search"&&<><input style={s.input} placeholder="Name, account, customer ID or mobile" value={query} onChange={event=>setQuery(event.target.value)}/><div style={s.results}>{matches.slice(0,300).map(row=><label key={key(row)} style={s.result}><input type="checkbox" checked={chosen.has(key(row))} onChange={()=>setChosen(previous=>{const next=new Set(previous);next.has(key(row))?next.delete(key(row)):next.add(key(row));return next;})}/><span>{value(row,"name")||"Unnamed"} · {value(row,"accountNo")||value(row,"enrolId")}</span></label>)}{matches.length>300&&<p>Showing first 300 matches. Narrow your search to select more.</p>}</div></>}
      {mode==="date"&&<div style={s.dates}><label>From Date<input type="date" style={s.input} value={from} onChange={event=>setFrom(event.target.value)}/></label><label>To Date<input type="date" style={s.input} value={to} onChange={event=>setTo(event.target.value)}/></label></div>}
      {mode==="range"&&<><p>Use exact Customer IDs in the current local record order (first → last).</p><input style={s.input} placeholder="First Customer ID" value={from} onChange={event=>setFrom(event.target.value)}/><input style={s.input} placeholder="Last Customer ID" value={to} onChange={event=>setTo(event.target.value)}/></>}
    </section><section style={s.options}><h3>Export Options</h3><label style={s.option}><input type="checkbox" checked={photos} onChange={event=>setPhotos(event.target.checked)}/> Include Customer Photo</label><label style={s.option}><input type="checkbox" checked={allFields} onChange={event=>setAllFields(event.target.checked)}/> Include All Fields</label><label style={s.option}><input type="checkbox" checked={resize} onChange={event=>setResize(event.target.checked)}/> Auto Resize Columns</label><div style={s.estimate}>Estimated Records: <strong>{filtered.length.toLocaleString()}</strong>{partial&&<p>Local download incomplete. Only available records can be exported.</p>}</div></section></div>}
    {error&&<p role="alert" style={{color:"#b42318"}}>{error}</p>}{progress&&<p role="status">{progress}</p>}
    <footer style={s.footer}><button onClick={controller.current?stop:close}>{controller.current?"Cancel Export":"Close"}</button><button style={s.export} disabled={loading||!!controller.current||!filtered.length} onClick={()=>void run()}>Export to Excel</button></footer>
  </div></div>;
}
const s:Record<string,React.CSSProperties>={backdrop:{position:"fixed",inset:0,zIndex:1000,background:"#061c34b8",display:"grid",placeItems:"center",padding:12},panel:{background:"#fff",color:"#152e49",width:"min(900px,100%)",maxHeight:"92dvh",overflow:"auto",borderRadius:16,padding:22,boxShadow:"0 24px 70px #0005"},header:{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start",marginBottom:20},close:{border:0,background:"transparent",fontSize:30,cursor:"pointer"},columns:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(min(100%,300px),1fr))",gap:22},modes:{display:"grid",gap:7,alignContent:"start"},choice:{display:"flex",gap:12,padding:13,border:"1px solid #d7e1ec",borderRadius:8,cursor:"pointer"},input:{width:"100%",boxSizing:"border-box",padding:10,borderRadius:8,border:"1px solid #b8c8da"},results:{maxHeight:180,overflow:"auto"},result:{display:"flex",gap:8,padding:5},dates:{display:"flex",gap:10,flexWrap:"wrap"},options:{background:"#f1f6fc",padding:16,borderRadius:10},option:{display:"block",padding:"9px 0"},estimate:{background:"#dcebf9",padding:14,marginTop:12,borderRadius:8},footer:{display:"flex",justifyContent:"space-between",gap:10,marginTop:20},export:{background:"#008b57",color:"white",border:0,borderRadius:8,padding:"11px 20px",fontWeight:700}};
