import {useEffect,useState} from 'react';
import {callBankSetuWorker} from './workerApi';
type Metric={used?:number;limit?:number;remaining?:number|null;unavailable?:string;sampledAt?:string;estimated?:boolean};
type Status={checkedAt:string;hosting:Metric;firestoreReads:Metric;firestoreWrites:Metric;cloudflare:Metric;presence:{admins?:number;users?:number;unavailable?:string;windowMinutes?:number;truncated?:boolean}};
export default function MasterSystemStatus(){
 const [data,setData]=useState<Status>();const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const refresh=()=>{setBusy(true);setError('');void callBankSetuWorker<Status>('/master-system-status',{}).then(setData).catch(reason=>setError(reason.message)).finally(()=>setBusy(false));};
 useEffect(()=>{refresh();},[]);
 const metric=(title:string,value:Metric|undefined,bytes=false)=><article key={title} style={{padding:14,background:'#153d4c',borderRadius:12}}><h3 style={{color:'white'}}>{title}</h3>{value?.unavailable?<p role="status">{value.unavailable}</p>:value?<><p>Used: {bytes?((value.used||0)/1048576).toFixed(1)+' MiB':value.used?.toLocaleString()}</p><p>Limit: {bytes?((value.limit||0)/1048576).toFixed(1)+' MiB':value.limit?.toLocaleString()}</p><p>Remaining{value.estimated?' (estimate)':''}: {value.remaining==null?'Unavailable':bytes?(value.remaining/1048576).toFixed(1)+' MiB':value.remaining.toLocaleString()}</p><small>Sample: {value.sampledAt?new Date(value.sampledAt).toLocaleString():'—'}</small></>:<p>Loading…</p>}</article>;
 return <section style={{background:'#0b2630',color:'#eef7f7',padding:20,borderRadius:16}}><h2 style={{color:'white'}}>Master · Usage & Online Status</h2><p>Firebase में एक single request quota नहीं है। नीचे Firestore document reads/writes और Hosting storage अलग दिखते हैं। Provider metrics delayed हो सकते हैं; यह billing counter नहीं है। Cloudflare remaining, Workers Free के 100,000/day reference limit पर estimate है; paid plan हो तो console देखें।</p><button disabled={busy} onClick={refresh}>{busy?'Loading…':'Refresh status'}</button>{error&&<p role="alert">{error}</p>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14,marginTop:16}}>{metric('Firebase Hosting · project storage',data?.hosting,true)}{metric('Firestore · reads today (Pacific reset)',data?.firestoreReads)}{metric('Firestore · writes today (Pacific reset)',data?.firestoreWrites)}{metric('Cloudflare · account requests today (UTC)',data?.cloudflare)}<article><h3 style={{color:'white'}}>Recently active clients</h3>{data?.presence.unavailable?<p>{data.presence.unavailable}</p>:<><p>Client Admin: {data?.presence.admins??'—'}</p><p>Client User: {data?.presence.users??'—'}</p><small>Active heartbeat within 7 minutes; exact live connection count नहीं है। {data?.presence.truncated?'Result limit reached.':''}</small></>}</article></div><p><a style={{color:'#64e6d0'}} href="https://console.firebase.google.com/project/banksetu-69e2f/usage" target="_blank" rel="noreferrer">Firebase usage console</a> · <a style={{color:'#64e6d0'}} href="https://dash.cloudflare.com/" target="_blank" rel="noreferrer">Cloudflare analytics console</a></p></section>;
}
