import { useEffect, useMemo, useRef, useState } from "react";
import { addDoc, collection, doc, getDocs, limit, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, where, type Unsubscribe } from "firebase/firestore";
import { auth, db } from "./firebase";
import "./SupportCenter.css";

type Conversation={id:string;clientUid:string;clientName:string;clientEmail:string;tenantId:string;lastMessage:string;updatedAt?:unknown;unreadForMaster:boolean;unreadForClient:boolean};
type Message={id:string;text:string;senderUid:string;senderRole:string;createdAt?:unknown};
type Announcement={id:string;title:string;body:string;global:boolean;recipientUids:string[];tenantIds:string[];createdAt?:unknown;createdBy:string};
type UserOption={uid:string;name:string;email:string;tenantId:string;role:string};
const masterRole=(role:string)=>["master_owner","master_admin","admin"].includes(role);
const when=(value:unknown)=>{const item=value as {toDate?:()=>Date};return item?.toDate?.().toLocaleString()||"Sending…";};
const profile=()=>({uid:auth.currentUser?.uid||"",name:sessionStorage.getItem("bankSetuUserName")||auth.currentUser?.displayName||auth.currentUser?.email||"User",email:auth.currentUser?.email||"",tenantId:sessionStorage.getItem("bankSetuTenantId")||"",role:sessionStorage.getItem("bankSetuAccountRole")||""});
function watchAnnouncements(role:string,receive:(items:Announcement[])=>void,fail:(reason:Error)=>void,max=50){const p=profile(),sources=isMasterRole(role)?[query(collection(db,"supportAnnouncements"),limit(max))]:[query(collection(db,"supportAnnouncements"),where("global","==",true),limit(max)),query(collection(db,"supportAnnouncements"),where("recipientUids","array-contains",p.uid),limit(max)),...(p.tenantId?[query(collection(db,"supportAnnouncements"),where("tenantIds","array-contains",p.tenantId),limit(max))]:[])];const groups=new Map<number,Announcement[]>();const publish=()=>receive([...new Map([...groups.values()].flat().map(item=>[item.id,item])).values()]);return sources.map((source,index)=>onSnapshot(source,snap=>{groups.set(index,snap.docs.map(item=>({id:item.id,...item.data()} as Announcement)));publish();},reason=>fail(reason)));}
const isMasterRole=masterRole;

export function useSupportUnread(accountRole:string){
  const [count,setCount]=useState(0);
  const announced=useRef(false);
  useEffect(()=>{const p=profile();if(!p.uid)return;let chat=0,ann=0,announcementsLoaded=false,readsLoaded=false;const update=()=>setCount(chat+ann);const stops:Unsubscribe[]=[];
    if(masterRole(accountRole))stops.push(onSnapshot(query(collection(db,"supportConversations"),limit(100)),snap=>{chat=snap.docs.filter(item=>item.data().unreadForMaster===true).length;update();},()=>undefined));
    else stops.push(onSnapshot(doc(db,"supportConversations",p.uid),snap=>{chat=snap.data()?.unreadForClient===true?1:0;update();},()=>undefined));
    let announcements:Announcement[]=[];let reads=new Set<string>();const recount=()=>{ann=announcements.filter(item=>!reads.has(item.id)).length;update();if(announcementsLoaded&&readsLoaded&&ann>0&&!announced.current){announced.current=true;const event=new Event("banksetu-notification") as Event&{detail:{type:string;title:string;message:string}};event.detail={type:"warning",title:"Unread support updates",message:`${ann} unread message or announcement update(s). Open Support to view them.`};window.dispatchEvent(event);}};
    stops.push(...watchAnnouncements(accountRole,items=>{announcements=items;announcementsLoaded=true;recount();},()=>undefined));
    stops.push(onSnapshot(query(collection(db,"supportAnnouncementReads"),where("userId","==",p.uid),limit(100)),snap=>{reads=new Set(snap.docs.map(item=>String(item.data().announcementId)));readsLoaded=true;recount();},()=>undefined));
    return()=>stops.forEach(stop=>stop());
  },[accountRole]);return count;
}

export default function SupportCenter({accountRole}:{accountRole:string}){
  const p=profile(),isMaster=masterRole(accountRole);
  const [tab,setTab]=useState<"chat"|"announcements"|"help"|"faq"|"request">("chat");
  const [conversations,setConversations]=useState<Conversation[]>([]),[selected,setSelected]=useState(isMaster?"":p.uid),[messages,setMessages]=useState<Message[]>([]),[messageLimit,setMessageLimit]=useState(50),[draft,setDraft]=useState(""),[users,setUsers]=useState<UserOption[]>([]),[error,setError]=useState("");
  const [announcementLimit,setAnnouncementLimit]=useState(50);
  const [announcements,setAnnouncements]=useState<Announcement[]>([]),[readIds,setReadIds]=useState<Set<string>>(new Set()),[announcementTitle,setAnnouncementTitle]=useState(""),[announcementBody,setAnnouncementBody]=useState(""),[target,setTarget]=useState<"all"|"user"|"clients">("all"),[targetUser,setTargetUser]=useState(""),[targetTenants,setTargetTenants]=useState<Set<string>>(new Set());
  useEffect(()=>{if(!p.uid)return;if(!isMaster)return onSnapshot(doc(db,"supportConversations",p.uid),snap=>setConversations(snap.exists()?[{id:snap.id,...snap.data()} as Conversation]:[]),reason=>setError(reason.message));return onSnapshot(query(collection(db,"supportConversations"),limit(100)),snap=>{const list=snap.docs.map(item=>({id:item.id,...item.data()} as Conversation)).sort((a,b)=>String(b.updatedAt||"").localeCompare(String(a.updatedAt||"")));setConversations(list);if(!selected&&list[0])setSelected(list[0].id);},reason=>setError(reason.message));},[isMaster,p.uid,selected]);
  useEffect(()=>{if(!isMaster)return;void getDocs(query(collection(db,"users"),limit(300))).then(snap=>setUsers(snap.docs.filter(item=>item.data().status==="approved"&&item.data().subscriptionStatus==="active").map(item=>({uid:item.id,name:String(item.data().name||item.data().displayName||item.data().email||"User"),email:String(item.data().email||""),tenantId:String(item.data().tenantId||""),role:String(item.data().role||"")})).filter(item=>!masterRole(item.role)))).catch(reason=>setError(reason.message));},[isMaster]);
  useEffect(()=>{if(!selected){setMessages([]);return;}const messagesQuery=query(collection(db,"supportConversations",selected,"messages"),orderBy("createdAt","desc"),limit(messageLimit));const stop=onSnapshot(messagesQuery,snap=>setMessages(snap.docs.map(item=>({id:item.id,...item.data()} as Message)).reverse()),reason=>setError(reason.message));const field=isMaster?"unreadForMaster":"unreadForClient";void updateDoc(doc(db,"supportConversations",selected),{[field]:false}).catch(()=>undefined);return stop;},[selected,isMaster,messageLimit]);
  useEffect(()=>{if(!p.uid)return;const stops=[...watchAnnouncements(accountRole,items=>setAnnouncements(items.sort((a,b)=>when(b.createdAt).localeCompare(when(a.createdAt)))),reason=>setError(reason.message),announcementLimit),onSnapshot(query(collection(db,"supportAnnouncementReads"),where("userId","==",p.uid),limit(200)),snap=>setReadIds(new Set(snap.docs.map(item=>String(item.data().announcementId)))),reason=>setError(reason.message))];return()=>stops.forEach(stop=>stop());},[p.uid,accountRole,announcementLimit]);
  const activeConversation=conversations.find(item=>item.id===selected);
  const startConversation=(user:UserOption)=>{setMessageLimit(50);setSelected(user.uid);setTab("chat");};
  const send=async()=>{const text=draft.trim();if(!text||!p.uid)return;setDraft("");setError("");try{let clientUid=p.uid,clientName=p.name,clientEmail=p.email,tenantId=p.tenantId;if(isMaster){const user=users.find(item=>item.uid===selected);if(!user)throw new Error("Select a user before sending.");clientUid=user.uid;clientName=user.name;clientEmail=user.email;tenantId=user.tenantId;}const ref=doc(db,"supportConversations",clientUid);await setDoc(ref,{clientUid,clientName,clientEmail,tenantId,lastMessage:text,updatedAt:serverTimestamp(),unreadForMaster:!isMaster,unreadForClient:isMaster},{merge:true});await addDoc(collection(ref,"messages"),{text,senderUid:p.uid,senderRole:accountRole,clientUid,tenantId,createdAt:serverTimestamp()});setSelected(clientUid);}catch(reason){setError(reason instanceof Error?reason.message:"Message could not be sent.");}};
  const publish=async()=>{if(!isMaster)return;const recipientUids=target==="user"&&targetUser?[targetUser]:[],tenantIds=target==="clients"?[...targetTenants]:[];if(!announcementTitle.trim()||!announcementBody.trim()||(target!=="all"&&!recipientUids.length&&!tenantIds.length)){setError("Enter title, message and a valid audience.");return;}try{await addDoc(collection(db,"supportAnnouncements"),{title:announcementTitle.trim(),body:announcementBody.trim(),global:target==="all",recipientUids,tenantIds,createdAt:serverTimestamp(),createdBy:p.uid});setAnnouncementTitle("");setAnnouncementBody("");setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Announcement could not be published.");}};
  const markRead=(item:Announcement)=>void setDoc(doc(db,"supportAnnouncementReads",`${p.uid}_${item.id}`),{userId:p.uid,announcementId:item.id,readAt:serverTimestamp()}).catch(reason=>setError(reason.message));
  const tenants=useMemo(()=>[...new Map(users.filter(user=>user.tenantId).map(user=>[user.tenantId,user])).values()],[users]);
  return <section className="support-page">
    <header className="support-hero"><div><span className="support-kicker">BANK SETU HELP DESK</span><h1>Support &amp; Communication</h1><p>Private help, updates and guides in one secure place.</p></div><a className="whatsapp-support" href="https://wa.me/917002513264?text=Hello%20Bank%20Setu%20Support" target="_blank" rel="noreferrer">◉ WhatsApp Support</a></header>
    <div className="support-tabs">{([['chat','💬','Private Chat'],['announcements','📣','Announcements'],['help','📘','Help & Guides'],['faq','❓','FAQs'],['request','🎫','Request Support']] as const).map(([id,icon,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{icon} {label}{id==="announcements"&&announcements.filter(item=>!readIds.has(item.id)).length>0&&<b>{announcements.filter(item=>!readIds.has(item.id)).length}</b>}</button>)}</div>
    {error&&<div className="support-error" role="alert">{error}</div>}
    {tab==="chat"&&<div className="chat-layout"><aside className="conversation-list"><h2>{isMaster?"User Conversations":"Master Admin Support"}</h2>{isMaster&&<div className="support-users">{users.map(user=><button key={user.uid} className={selected===user.uid?"selected":""} onClick={()=>startConversation(user)}><span>{user.name}<small>{user.email||user.tenantId}</small></span></button>)}</div>}{!isMaster&&<p className="empty-support">Send a private message to the Master Admin. Only your conversation is visible here.</p>}</aside><article className="chat-panel"><div className="chat-title"><strong>{isMaster?(activeConversation?.clientName||users.find(user=>user.uid===selected)?.name||"Select a user"):"Master Admin"}</strong><span>{messages.length} recent messages</span></div><div className="message-list">{messages.length>=messageLimit&&<button className="load-older" onClick={()=>setMessageLimit(value=>value+50)}>Load older messages</button>}{messages.length?messages.map(item=><div key={item.id} className={item.senderUid===p.uid?"message mine":"message"}><p>{item.text}</p><time>{when(item.createdAt)}</time></div>):<div className="empty-support">No messages yet. Start the conversation below.</div>}</div><div className="chat-compose"><textarea value={draft} maxLength={2000} placeholder="Type your message…" onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send();}}}/><button onClick={()=>void send()} disabled={!draft.trim()||(!selected&&isMaster)}>Send</button></div></article></div>}
    {tab==="announcements"&&<div className="announcement-layout">{isMaster&&<aside className="announcement-editor"><h2>Publish Announcement</h2><input value={announcementTitle} maxLength={120} placeholder="Announcement title" onChange={event=>setAnnouncementTitle(event.target.value)}/><textarea value={announcementBody} maxLength={3000} placeholder="Write announcement…" onChange={event=>setAnnouncementBody(event.target.value)}/><select value={target} onChange={event=>setTarget(event.target.value as typeof target)}><option value="all">All users</option><option value="user">Specific user</option><option value="clients">Selected clients</option></select>{target==="user"&&<select value={targetUser} onChange={event=>setTargetUser(event.target.value)}><option value="">Select user</option>{users.map(user=><option key={user.uid} value={user.uid}>{user.name} — {user.email}</option>)}</select>}{target==="clients"&&<div className="tenant-choices">{tenants.map(item=><label key={item.tenantId}><input type="checkbox" checked={targetTenants.has(item.tenantId)} onChange={()=>setTargetTenants(old=>{const next=new Set(old);next.has(item.tenantId)?next.delete(item.tenantId):next.add(item.tenantId);return next;})}/>{item.name} ({item.tenantId})</label>)}</div>}<button onClick={()=>void publish()}>Publish securely</button></aside>}<div className="announcement-feed"><h2>Announcements</h2>{announcements.length?announcements.map(item=><article key={item.id} className={readIds.has(item.id)?"announcement read":"announcement unread"}><div><h3>{item.title}</h3><time>{when(item.createdAt)}</time></div><p>{item.body}</p>{!readIds.has(item.id)&&<button onClick={()=>markRead(item)}>Mark as read</button>}</article>):<div className="empty-support">No announcements are available for your account.</div>}{announcements.length>=announcementLimit&&<button className="load-older" onClick={()=>setAnnouncementLimit(value=>value+50)}>Load older announcements</button>}</div></div>}
    {tab==="help"&&<div className="support-content-grid"><article><h2>Customer &amp; Sync Guide</h2><ol><li>Save the customer locally first.</li><li>Open Sync &amp; Backup to check pending uploads.</li><li>Use Sync Now when the internet returns.</li><li>Keep pending changes resolved before local reset.</li></ol></article><article><h2>Backup Guide</h2><ol><li>Create a local backup before major device changes.</li><li>Use Export to Excel for readable customer reports.</li><li>Restore only a Bank Setu backup file for this workspace.</li></ol></article></div>}
    {tab==="faq"&&<div className="faq-list"><details><summary>Why does Upload Pending show a number?</summary><p>The record is saved locally and is waiting for verified Google Sheet or Drive confirmation.</p></details><details><summary>Can I work without internet?</summary><p>Approved offline access keeps local customer work available until the verified offline session expires.</p></details><details><summary>Will Reset Local Database delete Google data?</summary><p>No. The reset clears the current tenant local customer cache and downloads valid cloud records again after safety checks.</p></details><details><summary>Who can see my support chat?</summary><p>Your authenticated account and authorized Master Admin can access the conversation. Other tenants cannot read it.</p></details></div>}
    {tab==="request"&&<div className="request-card"><h2>Request Support</h2><p>Describe the issue in Private Chat for a tracked in-app reply, or open WhatsApp for urgent assistance.</p><div><button onClick={()=>setTab("chat")}>Open Private Chat</button><a href="https://wa.me/917002513264?text=Hello%20Bank%20Setu%20Support" target="_blank" rel="noreferrer">Open WhatsApp</a></div></div>}
  </section>;
}
